In [27]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization, LayerNormalization

In [28]:
# Create a random dataset
np.random.seed(42)

input_data = np.random.randint(1, 100, size=(5, 4)).astype(np.float32)

print("Original Input Values:")
print(input_data)

Original Input Values:
[[52. 93. 15. 72.]
 [61. 21. 83. 87.]
 [75. 75. 88. 24.]
 [ 3. 22. 53.  2.]
 [88. 30. 38.  2.]]


In [29]:
# Convert NumPy array into TensorFlow tensor
input_tensor = tf.convert_to_tensor(input_data)

print("Tensor Shape:", input_tensor.shape)

Tensor Shape: (5, 4)


In [30]:
# Create Batch Normalization layer
batch_norm = BatchNormalization()

# Apply Batch Normalization
batch_output = batch_norm(input_tensor, training=True)

print("Batch Normalization Output:")
print(batch_output.numpy())

Batch Normalization Output:
[[-0.13057256  1.4961945  -1.4722178   0.9714192 ]
 [ 0.17867827 -0.90840393  1.0057726   1.3925549 ]
 [ 0.65973496  0.8950449   1.1879778  -0.37621444]
 [-1.8142712  -0.87500674 -0.08745849 -0.9938799 ]
 [ 1.1064308  -0.6078291  -0.6340741  -0.9938799 ]]


In [31]:
# Create Layer Normalization layer
layer_norm = LayerNormalization()

# Apply Layer Normalization
layer_output = layer_norm(input_tensor)

print("Layer Normalization Output:")
print(layer_output.numpy())

Layer Normalization Output:
[[-0.20870328  1.2174368  -1.4957078   0.48697472]
 [-0.07636023 -1.6035662   0.763603    0.9163234 ]
 [ 0.38711047  0.38711047  0.91684055 -1.6910613 ]
 [-0.82316875  0.09684336  1.5979159  -0.8715905 ]
 [ 1.5630928  -0.30617273 -0.04834306 -1.2085768 ]]


In [32]:
print("========== ORIGINAL INPUT ==========")
print(input_data)

print("\n========== BATCH NORMALIZATION OUTPUT ==========")
print(batch_output.numpy())

print("\n========== LAYER NORMALIZATION OUTPUT ==========")
print(layer_output.numpy())

========== ORIGINAL INPUT ==========
[[52. 93. 15. 72.]
 [61. 21. 83. 87.]
 [75. 75. 88. 24.]
 [ 3. 22. 53.  2.]
 [88. 30. 38.  2.]]

========== BATCH NORMALIZATION OUTPUT ==========
[[-0.13057256  1.4961945  -1.4722178   0.9714192 ]
 [ 0.17867827 -0.90840393  1.0057726   1.3925549 ]
 [ 0.65973496  0.8950449   1.1879778  -0.37621444]
 [-1.8142712  -0.87500674 -0.08745849 -0.9938799 ]
 [ 1.1064308  -0.6078291  -0.6340741  -0.9938799 ]]

========== LAYER NORMALIZATION OUTPUT ==========
[[-0.20870328  1.2174368  -1.4957078   0.48697472]
 [-0.07636023 -1.6035662   0.763603    0.9163234 ]
 [ 0.38711047  0.38711047  0.91684055 -1.6910613 ]
 [-0.82316875  0.09684336  1.5979159  -0.8715905 ]
 [ 1.5630928  -0.30617273 -0.04834306 -1.2085768 ]]


In [33]:
print("Batch Normalization:")
print("- Batch Normalization normalizes the input across the batch.")
print("- It helps speed up training and improves model stability.")

print("\nLayer Normalization:")
print("- Layer Normalization normalizes the features of each individual sample.")
print("- It works well for recurrent networks and small batch sizes.")

print("\nDifference:")
print("- Batch Normalization uses batch statistics, while Layer Normalization uses feature statistics for each sample.")

Batch Normalization:
- Batch Normalization normalizes the input across the batch.
- It helps speed up training and improves model stability.

Layer Normalization:
- Layer Normalization normalizes the features of each individual sample.
- It works well for recurrent networks and small batch sizes.

Difference:
- Batch Normalization uses batch statistics, while Layer Normalization uses feature statistics for each sample.
